export const data = {
  response: [
    {
      name: 'S3',
      type: 'connector',
      category: 'Amazon Web Services',
      description: 'Connection to access data in Amazon S3.',
      className: 'io.cdap.plugin.aws.s3.connector.S3Connector',
      artifact: {
        name: 'amazon-s3-plugins',
        version: '1.16.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'File',
      type: 'connector',
      category: 'File',
      description: 'Connection to browse and sample data from the local file system.',
      className: 'io.cdap.plugin.batch.connector.FileConnector',
      artifact: {
        name: 'core-plugins',
        version: '2.8.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'Database',
      type: 'connector',
      category: 'Database',
      description: 'Connection to access data in relational databases using JDBC.',
      className: 'io.cdap.plugin.db.connector.DBConnector',
      artifact: {
        name: 'database-plugins',
        version: '2.8.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'BigQuery',
      type: 'connector',
      category: 'Google Cloud Platform',
      description: 'Connection to access data in BigQuery datasets and tables.',
      className: 'io.cdap.plugin.gcp.bigquery.connector.BigQueryConnector',
      artifact: {
        name: 'google-cloud',
        version: '0.19.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'GCS',
      type: 'connector',
      category: 'Google Cloud Platform',
      description: 'Connection to access data in Google Cloud Storage.',
      className: 'io.cdap.plugin.gcp.gcs.connector.GCSConnector',
      artifact: {
        name: 'google-cloud',
        version: '0.19.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'Spanner',
      type: 'connector',
      category: 'Google Cloud Platform',
      description: 'Connection to access data in Spanner databases and tables.',
      className: 'io.cdap.plugin.gcp.spanner.connector.SpannerConnector',
      artifact: {
        name: 'google-cloud',
        version: '0.19.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'Kafka',
      type: 'connector',
      category: 'Messaging Systems',
      description: 'Connection to access data in Kafka topics.',
      className: 'io.cdap.plugin.connector.KafkaConnector',
      artifact: {
        name: 'kafka-plugins',
        version: '2.7.0-0.10.2.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'SQL Server',
      type: 'connector',
      category: 'Database',
      description: 'Connection to access data in SQL Server databases using JDBC.',
      className: 'io.cdap.plugin.mssql.SqlServerConnector',
      artifact: {
        name: 'mssql-plugin',
        version: '1.7.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'MySQL',
      type: 'connector',
      category: 'Database',
      description: 'Connection to access data in Mysql databases using JDBC.',
      className: 'io.cdap.plugin.mysql.MysqlConnector',
      artifact: {
        name: 'mysql-plugin',
        version: '1.7.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'Oracle',
      type: 'connector',
      category: 'Database',
      description: 'Connection to access data in Oracle databases using JDBC.',
      className: 'io.cdap.plugin.oracle.OracleConnector',
      artifact: {
        name: 'oracle-plugin',
        version: '1.7.0',
        scope: 'SYSTEM',
      },
    },
    {
      name: 'PostgreSQL',
      type: 'connector',
      category: 'Database',
      description: 'Connection to access data in PostgreSQL databases using JDBC.',
      className: 'io.cdap.plugin.postgres.PostgresConnector',
      artifact: {
        name: 'postgresql-plugin',
        version: '1.7.0',
        scope: 'SYSTEM',
      },
    },
  ],
};
