export const PLEASE_SELECT_THE_DELIMITER = 'Please select the delimiter';
export const COMMA = 'Comma';
export const TAB = 'Tab';
export const SPACE = 'Space';
export const PIPE = 'Pipe';
export const CAP_A = '^A';
export const CAP_D = '^D';
export const CUSTOM_DELIMITER = 'Custom delimiter';
export const SET_FIRST_ROW_AS_HEADER = 'Set first row as header';
