# Copyright © 2022 Cask Data, Inc.
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CDAP UI Unit and Integration Tests

on:
  workflow_run:
    workflows:
      - Trigger build
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion != 'skipped' }}
    
    strategy:
      matrix:
        node-version: [10.16]
        java-version: [8]

    # Cancel ongoing runs
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2

    # installing dependency for node-canvas
    - name: Install Ubuntu debendency
      run: sudo apt-get install -y libgif-dev

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    # installing Java 8 to run the sandbox
    - name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Download CDAP Sandbox and Start it
      env:
        GCP_PROJECTID: ${{ secrets.GCP_PROJECTID }}
        GCP_SERVICE_ACCOUNT_CONTENTS: ${{ secrets.GCP_SERVICE_ACCOUNT_CONTENTS }}
        GCP_SERVICE_ACCOUNT_PATH: '${{ github.workspace }}/key_file.json'
      run: |
        echo $GCP_PROJECTID # Will remove after test in develop - git will show secrets as ***
        echo $GCP_SERVICE_ACCOUNT_PATH # Will remove after test in develop - git will show secrets as ***
        echo $GCP_SERVICE_ACCOUNT_CONTENTS > ./key_file.json
        cd sandboxjs
        npm install -g yarn # Install Yarn globally
        yarn --frozen-lockfile # Install sandbox runner dependencies 
        yarn setup-gitpod $JAVA_HOME # Fetch and start sandbox
        sudo pkill -f node # Kill the sandbox UI

    - name: Install UI Dependencies
      run: |
        yarn --frozen-lockfile
        yarn run bower-root # Install Bower dependencies
    - name: Start CDAP-UI and run the tests
      run: |
        Xvfb :1 -screen 0 1024x768x24 & export DISPLAY=:1 # Set Display port
        yarn run cdap-full-build-more-memory # Build UI
        yarn start & > server.out
        yarn run test:unit
        yarn run test:integration
